Fixed broken absolute links
gardener/documentation pull request #282
Opened 2021-09-23 10:59 UTC by n-boshnakov

**What this PR does / why we need it**:
This PR fixes broken absolute links and removes broken links from the manifest
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```improvement developer
NONE
```

2021-09-23 11:00 UTC, n-boshnakov commented
/review @Kristian-ZH

2021-09-29 07:02 UTC, Kristian-ZH requested changes
Can you please address these comments?

2021-09-29 07:02 UTC, Kristian-ZH commented on website/documentation/tutorials/shoot_istio_dns_certs/_index.md
> +1. The [External DNS Manager](https://gardener.cloud/docs/concepts/networking/dns-managment/), provided to you as a service (`dns.gardener.cloud/class: garden`), picks up the request and creates the
I prefer on github page to be used a github links -  https://github.com/gardener/external-dns-management/blob/master/README.md

2021-09-30 07:18 UTC, n-boshnakov commented on website/blog/2020-10/00/Gardener-Integrates-with-KubeVirt.md
> +The **Infrastructure Controller** configures the network communication between the shoot worker nodes. By default, shoot worker nodes only use the provider cluster’s pod network. To achieve higher le
Did you mean another link? You have given the exact same link I have placed the file.

2021-09-30 08:02 UTC, Kristian-ZH commented on website/blog/2020-10/00/Gardener-Integrates-with-KubeVirt.md
> +The **Infrastructure Controller** configures the network communication between the shoot worker nodes. By default, shoot worker nodes only use the provider cluster’s pod network. To achieve higher le
my mistake, the link is correct

2021-09-30 08:03 UTC, Kristian-ZH submitted a review, later dismissed
/lgtm

2021-09-30 08:35 UTC, Kristian-ZH approved these changes

2021-09-30 08:35 UTC, merged