Added Kubernetes Hardening security guide
gardener/documentation pull request #441
Opened 2023-11-06 13:04 UTC by n-boshnakov

**What this PR does / why we need it**:
This PR adds the Kubernetes Hardening guide in order to inform stakeholders on their responsibilities in keeping their clusters secure.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement developer
Added Kubernetes Hardening security guide
```

2023-11-06 14:25 UTC, JordanJordanov commented on website/documentation/guides/kubernetes-hardening/_index.md
> +The Gardener team takes security very seriously, which is why we mandate the Security Technical Implementation Guide (STIG) for Kubernetes as published by the Defense Information Systems Agency (DISA
> Thus, Gardener has decided and aligned with SGS to adopt and show SCR03 compliance with the DISA Kubernetes STIGs.

This sentence should be deleted. We shall not mention SGS in the public site (at least not as of today).
We shall rethink the whole paragraph.

2023-11-06 14:25 UTC, JordanJordanov commented on website/documentation/guides/kubernetes-hardening/_index.md
> +The Gardener team takes security very seriously, which is why we mandate the Security Technical Implementation Guide (STIG) for Kubernetes as published by the Defense Information Systems Agency (DISA
On top of that, probably as additional public page, we shall list all rules, which are responsibility to Service Provider (this can be a 2nd step)

2023-11-06 14:25 UTC, JordanJordanov commented on website/documentation/guides/kubernetes-hardening/_index.md
> +The Gardener infrastructure is taking care of the rules which are part of DISA Kubernetes STIGs but not listed here (secure-by-design/code).
> The Gardener infrastructure is taking care of the rules which are part of DISA Kubernetes STIGs but not listed here (secure-by-design/code).

This sentence is not guaranteed to be true outside SAP, is it?

2023-11-06 14:40 UTC, JordanJordanov requested changes

2023-11-07 06:53 UTC, JordanJordanov commented on website/documentation/guides/kubernetes-hardening/_index.md
> +The Gardener team takes security very seriously, which is why we mandate the Security Technical Implementation Guide (STIG) for Kubernetes as published by the Defense Information Systems Agency (DISA
@n-boshnakov IMHO we shall remove SCR03 as well.

2023-11-07 08:11 UTC, JordanJordanov commented on website/documentation/guides/kubernetes-hardening/_index.md
> +The Gardener team takes security very seriously, which is why we mandate the Security Technical Implementation Guide (STIG) for Kubernetes as published by the Defense Information Systems Agency (DISA
```suggestion
The Gardener team takes security seriously, which is why we mandate the Security Technical Implementation Guide (STIG) for Kubernetes as published by the Defense Information Systems Agency (DISA) [here](https://public.cyber.mil/stigs/downloads/). We offer Gardener adopters the opportunity to show compliance with DISA Kubernetes STIG via the compliance checker tool [diki](https://github.com/gardener/diki). The latest release in machine readable format can be found in the [STIGs Document Library](https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform) by searching for Kubernetes.
```

2023-11-07 08:22 UTC, ThormaehlenFred submitted a review, later dismissed
/lgtm

2023-11-07 08:38 UTC, JordanJordanov approved these changes
/lgtm

2023-11-07 08:40 UTC, merged