Make access to logging and monitoring more self-explanatory from the …
gardener/documentation pull request #464
Opened 2024-01-19 11:49 UTC by BeckerMax

…docs

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-01-19 13:43 UTC, n-boshnakov requested changes

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +![](./images/welcome_plutono.png)
I can't seem to find this image in the PR, or any of the other newly added images.

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +After logging in you will be greeted with a Plutono welcome screen. Click on `General/Home` at the top as depicted with the red arrow in the next picture:
```suggestion
After logging in, you will be greeted with a Plutono welcome screen. Navigate to `General/Home`, as depicted with the red arrow in the next picture:
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +- `Kubernetes Control Plane Status` if you want to check control plane availability during a certain time frame go to the this dashboard.
```suggestion
- The `Kubernetes Control Plane Status` dashboard allows you to check control plane availability during a certain time frame.
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +- The `API Server` dashboard gives you an overview which requests are done towards your apiserver and how long they take.
```suggestion
- The `API Server` dashboard gives you an overview on which requests are done towards your apiserver and how long they take.
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +Vali is our logging solution. In order to access the logs provided by Vali first log into Plutono as describe [here](https://gardener.cloud/docs/getting-started/observability/components/#logging-into
```suggestion
Vali is our logging solution. In order to access the logs provided by Vali, you need to:

1. Log into Plutono, as described [here](https://gardener.cloud/docs/getting-started/observability/components/#logging-into-Plutono).
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +Then click on Explore which is depicted as the little compass symbol. See the red arrow in the next picture for where to click:
```suggestion
2. Choose `Explore`, which is depicted as the little compass symbol:
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +Then select `Vali` at the top left as shown here:
```suggestion
3. Select `Vali` at the top left, as shown here:
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +Helpful queries would be for example:
```suggestion
Here are some examples of helpful queries:
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> +- `{unit="containerd.service", nodename="ip-123"}` retrieves the containerd logs for a specific node
```suggestion
- `{unit="kubelet.service", nodename="ip-123"}` to get the kubelet logs of a specific node.
- `{unit="containerd.service", nodename="ip-123"}` to retrieve the containerd logs for a specific node.
```

2024-01-19 13:43 UTC, n-boshnakov commented on website/documentation/getting-started/observability/components.md
> + For more information also how to retrieve K8s events from the past see [How to access Logs](https://github.com/gardener/gardener/blob/master/docs/usage/logging.md#how-to-access-the-logs)
```suggestion
 Choose `Help >` in order to see what options exist to filter the results.

 For more information on how to retrieve K8s events from the past, see [How to Access Logs](https://github.com/gardener/gardener/blob/master/docs/usage/logging.md#how-to-access-the-logs).
```

2024-01-23 07:41 UTC, n-boshnakov approved these changes
/lgtm

2024-01-23 07:57 UTC, JordanJordanov approved these changes
/lgtm

2024-01-23 12:31 UTC, merged